### ISSUE TITLE
Task Return Result Content

### ISSUE THREAD

**Issue by eeintech** [czue/celery-progress#66]
I updated one of my application from `0.0.10` to `0.0.14` and now running into issue where my custom `onSuccess` function is not able to access the `result` content. Here is a snapshot of it:
``` js
function processSuccess(progressBarElement, progressBarMessageElement, result) {
		console.log('SUCCESS: ' + result)
		var search_id = result[0]
		var datasheet = result[1]
		var payload = {
			"search_id" : search_id,
			"datasheet" : datasheet,
		}
		console.log(payload)

                ....
}
```
(`result` is now empty).

And here is the task:
``` python
@shared_task(bind=True)
def ProcessDownload(self, manufacturer, part_number, search_id):
	progress_recorder = ProgressRecorder(self)
	progress_recorder.set_progress(0, 10, description='Initializing Request')
	time.sleep(1)

	spec = Specifications(task=self)
	spec.DownloadPDF(manufacturer, part_number)

	if not spec.datasheet:
		return [search_id, '']
	
	return [search_id, capspec.datasheet]
```

This code used to work and the `processSuccess` would capture the content of `result` but no anymore... I've added those debug prints to make sure the `processSuccess` method is called (which is the case).
I've also changed the task return value to a simple string for testing purpose and still nothing.

Any idea what am I missing? Was this setup wrong in the first place?
How should one efficiently implement the "communication" between the task return values and the `result` input of the `onSuccess` method?

**Comment by OmarWKH** [comment]
I think this is caused by fixing https://github.com/czue/celery-progress/issues/44. Sometimes the result is not passed to some handlers to avoid showing it in multiple places.

To address this, we could let the default handlers decide for themselves to show the result or not.

**Comment by eeintech** [comment]
@OmarWKH Thanks but I'm not entirely sure I grasp the idea... What is the correct way to "pass the result to the handler"?

**Comment by czue** [comment]
@eeintech sorry about this!

I just tried testing it out and I'm not able to reproduce it. Here's my task:

```python
@shared_task(bind=True)
def progress_bar_task(self, seconds, fail=False):
    progress_recorder = ProgressRecorder(self)
    count = seconds * 10
    for i in range(count):
        time.sleep(.1)
        if i > count / 2 and fail:
            raise Exception('fail!')
        progress_recorder.set_progress(i + 1, count)

    return 'done'
```
and custom `onSuccess` function:

```javascript
function onSuccess(progressBarElement, progressBarMessageElement, result) {
  console.log('result is', result);
}
```
`result` is correctly printed (and also when I change it to a list). did you make any other changes while you upgraded? Are you sure your result backend is working? Also, have you checked whether downgrading restores the working behavior?

**Comment by czue** [comment]
(can you also paste how you're calling `CeleryProgressBar.initProgressBar`?)

**Comment by OmarWKH** [comment]
> @OmarWKH Thanks but I'm not entirely sure I grasp the idea... What is the correct way to "pass the result to the handler"?

Sorry, I meant this line:
https://www.github.com/czue/celery-progress/tree/master/celery_progress%2Fstatic%2Fcelery_progress%2Fcelery_progress.js#L101

The result is processed by `getMessageDetails` before being passed to `onSuccess`. `getMessageDetails` returns an empty value if there's a resultElement to avoid showing the result twice in the page.

To check if this is the cause or not, try removing the result element from your page.

**Comment by eeintech** [comment]
@OmarWKH Yes that's it! I removed the `<div id="celery-result">` and now my `processSuccess` method is getting the right `result`!

This is a snapshot of my custom `onResult` method:
``` js
function processResult(resultElement, result) {
		console.log('RESULT')
		var datasheet_url = result[1]
		if (datasheet_url) {
			var result_html = '... html code ...'
		} else {
			var result_html = '... html code ...'
		}
		resultElement.innerHTML = result_html;
	}
```

Of course now I get an error for setting the `resultElement.innerHTML` because it can't find the resultElement.

I'm not sure how to work around this potential bug (or is it my usage which is incorrect?).

@czue Yes you are right, it works without the result element, but adding it seems to trigger this issue.

**Comment by EJH2** [comment]
As Omar has pointed out, this issue stems from the fix that was implemented in #45, specifically how the `getMessageDetails` function is applied. If the result element is present, then `getMessageDetails` will override the result passed to the success handler to nothing, as is seemingly consistent with your issue here. A remedy for this would to just pass the raw result to the handler, and move the `getMessageDetails` wrapping to the handlers instead. An example is provided below.
```js
onSuccessDefault(progressBarElement, progressBarMessageElement, result) {
    result = this.getMessageDetails(result);
    progressBarElement.style.backgroundColor = this.barColors.success;
    progressBarMessageElement.textContent = "Success! " + result;
}
```
The same would apply for the `onTaskError`. With this change, we would maintain current default functionality while also allowing users to override the behavior if needed.

**Comment by eeintech** [comment]
@EJH2 I like it! I tested and it works with your proposed change and:
``` js
            if (data.success === true) {
                this.onSuccess(this.progressBarElement, this.progressBarMessageElement, data.result);
            }
```

Now I don't know the best way to test on `onTaskError` though, is it more or like changing the code as follow?

``` js
static onErrorDefault(progressBarElement, progressBarMessageElement, excMessage, data) {
        result = this.getMessageDetails(data.result);
        progressBarElement.style.backgroundColor = '#dc4f63';
        excMessage = excMessage || '';
        progressBarMessageElement.textContent = "Uh-Oh, something went wrong! " + excMessage;
    }
```

and:
``` js
            } else if (data.success === false) {
                this.onTaskError(this.progressBarElement, this.progressBarMessageElement, data);
            }
```

**Comment by OmarWKH** [comment]
1. onTaskError is more challenging because it shares code with states with different desired behaviors. This is how states map to handlers currently:
- success: onSuccess
- failure: onTaskError -> onError
- retry: onRetry -> onTaskError -> onError 
- revoked: onTaskError -> onError
- ignored: onIgnored
- unknown states: onTaskError -> onError
- other errors (onDataError, onNetworkError, and onHttpError): onError

(I omitted states which have no result like PROGRESS)

2. Some states delete the result before it gets to the onResult handler. So that handler might have a similar issue to this thread.

3. The result field is used to communicate different things for different states.

Agreeing on some requirements will make this easier to solve.

There are two behaviors:

Behavior 1: if result element exists, print result in result element; otherwise, print it in progress bar message. 

Behavior 2: print "result" in progress bar message only.

Suggested requirements:

**Which states need behavior 1?**
- success
- failure 

**Which states need behavior 2?**
- retry
- revoked
- ignored
- unknown states
- also other errors (network, http, ..)

**Should the onResult handler get results for states with behavior 2?**
I think no, but I'm not sure.

**Comment by EJH2** [comment]
I meant `onErrorDefault` instead of `onTaskError` in my previous comment, I should probably not have written it while tired.

I don't necessarily think we need to overhaul our current system too heavily as a result of this, as with the minor change everything should work as intended.

For your behavior analysis, I had sort of the same thoughts while implementing the newer states. The retry state is just an intermediary transition, so no need to be put in the result element as it's still ongoing. For ignored, there really is no result, so I opted to drop that as well. Revoked states could be considered a result, but I leaned more towards treating it like ignored for the sake of clarity. Unknown states have sat in a weird position for me as there's an ungodly amount of ways to interpret them for any number of different user implementations, so I opted to leave those alone. Hopefully that gives you some idea of how I approached it.

**Comment by czue** [comment]
Glad you all were able to get to the bottom of this and sorry for my role in introducing it!

I'm pro rolling out the change suggested by @EJH2 here https://github.com/czue/celery-progress/issues/66#issuecomment-727137648 - were you going to PR that or do you want someone else to do it?

**Comment by eeintech** [comment]
@czue I opened PR #67 with the proposed change that fixed my issue. I'll leave it up to @OmarWKH and @EJH2 to decide how to move forward with the `onError` behavior :smile:
